### ISSUE TITLE
Hovering about the current action button results in a infinite loop

### ISSUE THREAD

**Issue by jlnostr** [vtnorton/Heartthrob#3]
Hiya, first of all, thanks for this nice project.

When I opened your [demo page](http://heartthrob.vtnorton.com/onlycss.html) and scrolled down to the "buttons & links" section, hovering about the current action button results in a strange infinite loop for the opening animation. I've recorded the issue and uploaded the video to [OneDrive](https://1drv.ms/v/s!An83x2xGjRofj6ZvWyAtgx6vSmianA), but it should be easy to reproduce the issue.

Tested in Firefox 66 and Chromium 71.

**Comment by vtnorton** [comment]
Hey thanks for the feedback. 

I struggled with this bug a few months ago, I tried to fix it with only CSS but it's beyond my capabilities. As far as I know it will need to be recreated with javascript effects somehow.

**Comment by vtnorton** [comment]
This component will be moved to the heartthrob-react project.
