### ISSUE TITLE
Sugesting ESLint to get a better code quality

### ISSUE THREAD

**Issue by NathanPB** [vtnorton/Heartthrob#5]
I was reading the project source and I found some bad/not too good practices. So here I am.
I suggest the project to use the [ESLint](https://eslint.org) linting utility, it will help (and force) the developers to use better practices, that will bring best code quality.

**Comment by vtnorton** [comment]
I didn't knew about ESLint, but I'm already in love with a few minutes studing it. I will add to the project. Thank you so much showing me a really cool thing.

**Comment by vtnorton** [comment]
I added ESLint to the project - Airbnb style - but I will need help to fix all of the issues [and man-o-man, there is a lot!] 

Maybe I should went to the Standart style instead.
